### ISSUE TITLE
Guild Wars 2 Graphical Error

### ISSUE THREAD

**Issue by Ghostkat9** [megai2/d912pxy#330]
When previewing certain mount and weapon skins, the visual effects display improperly, like the vertical banding you see below. This is especially bad while trying to preview some of the finishers, where it takes up the entire vertical area of the window, but it's most prominently experienced when you try and preview any of the Primeval mount skins.

![gw230](https://user-images.githubusercontent.com/71421958/106351353-a05a0980-6290-11eb-9179-7ff09be38963.jpg)

I noticed that the banding itself changes when you try to move the window around, like it's trying to sample from the colours in the background.

![gw231](https://user-images.githubusercontent.com/71421958/106351359-a8b24480-6290-11eb-9002-6ef4bb66771d.jpg)
![gw232](https://user-images.githubusercontent.com/71421958/106351362-acde6200-6290-11eb-9b23-c4d49c67201f.jpg)

I'm using an NVidia GTX 1080TI, i9-9900K CPU, 32GB DDR4 RAM, I've followed all the troubleshooting instructions thus far and everything else seems to be up-to-date.

Here's my log file 
[log.txt](https://github.com/megai2/d912pxy/files/5897595/log.txt)

**Comment by Ghostkat9** [comment]
Also I don't know how to add the labels? I looked everywhere and can't see where to add one. Sorry about not putting one!

**Comment by megai2** [comment]
All renders fine for me on 2.4RC3

![изображение](https://user-images.githubusercontent.com/1693251/106486177-6d975780-64c2-11eb-9125-21ef4f929cae.png)
![изображение](https://user-images.githubusercontent.com/1693251/106486262-830c8180-64c2-11eb-96d5-e7e469117c09.png)

Please share what gfx settings you use.

**Comment by Ghostkat9** [comment]
I have everything on the highest possible settings. The latest version of the d912pxy plugin I'm using is v2.3.1h2, which is the latest one currently available from the Guild Wars 2 Addon Manager (no further updates are available for the plugin there, so I don't have 2.4RC3).

**Comment by Ghostkat9** [comment]
So I just discovered an additional bit of information I wanted to share. I double-checked your options against the graphics settings I was using, and found that my render sampling was set to Supersample, as I have a GTX 1080TI. When I switched it to Native, like you have, it was fixed. I prefer the quality of Supersample, and with an i9 and GTX card my computer can handle it with a lot going on the screen, so I'd prefer not to drop down in quality if possible. Would it be possible to get this fixed for Supersample? Thanks :)

**Comment by Ghostkat9** [comment]
(also, out of curiosity, how do you add the labels to the threads here in Github? I can't figure it out XD Thanks! :) )

**Comment by megai2** [comment]
Labels can be added in right-top menu

And for me it still working fine with supersample, so i guess it is fixed in 2.4
![изображение](https://user-images.githubusercontent.com/1693251/106617276-83b71d80-657f-11eb-9fe5-de0955901591.png)

**Comment by Ghostkat9** [comment]
Weird, I don't see any menu on the top right to alter the label. I see where it says Labels and Assignees, but no menus which allow me to set or designate the labels themselves. That area isn't clickable for me for some reason.

**Comment by megai2** [comment]
2.4 released, if problem persists - reopen issue please.

**Comment by Ghostkat9** [comment]
The problem still persists even after the 2.4 release, except now some of the bands "flicker" and appear more wavy and numerous. Here are screenshots. 
![gw441](https://user-images.githubusercontent.com/71421958/106952685-45883e00-66e6-11eb-9edd-518b9f034da9.jpg)
![gw442](https://user-images.githubusercontent.com/71421958/106952755-618bdf80-66e6-11eb-8ac8-cd035b1f20fb.jpg)

**Comment by Ghostkat9** [comment]
Here's the log file. 

[log.txt](https://github.com/megai2/d912pxy/files/5928402/log.txt)

I also noticed a similar effect happens when I preview the Mad Realm mount skins. Areas which should be transparent aren't presented properly in the preview, so I think maybe this could possibly be related to the water reflections issue someone else was having? It appears to be a problem with presenting transparency and translucency, and/or reflections. I have also noticed that the colours on the banding in the previews shift when the camera is moved around.

Here is the Mad Realm Raptor as it appears in the preview:
![gw445](https://user-images.githubusercontent.com/71421958/106953800-ab28fa00-66e7-11eb-86aa-08ddc955992e.jpg)

Here is the Mad Realm Raptor as it appears when it is summoned:
![gw446](https://user-images.githubusercontent.com/71421958/106953852-c0058d80-66e7-11eb-8dd2-d9ed82731fc7.jpg)

Hopefully this sheds some light on where the root of the problem may be.

Again, the issue is fixed if I swap from Supersample to Native, but otherwise here are my graphics settings:

![gw447](https://user-images.githubusercontent.com/71421958/106954138-36a28b00-66e8-11eb-875f-b19f836162ca.jpg)
![gw448](https://user-images.githubusercontent.com/71421958/106954155-3d310280-66e8-11eb-8c5b-d4b30adc3498.jpg)

I have also tried turning on and off Effect LOD to see if that would perhaps make any difference, just in case, but nope.

**Comment by Ghostkat9** [comment]
> 2.4 released, if problem persists - reopen issue please.

Also I don't think I can reopen this issue, since you closed it. I think you have to be the one to reopen it. I don't see any option on my end which shows how to reopen it if you closed it. But I would like to reopen it since it's a persisting issue.

**Comment by megai2** [comment]
Hm, i still can't repro it
![изображение](https://user-images.githubusercontent.com/1693251/106957000-7e58ff00-6748-11eb-8924-677ac29f1f4c.png)
Do you have any other addons/overlays by chance?

**Comment by Ghostkat9** [comment]
The only addons I have are the radial mount menu and yours, and that's it. I sometimes use TacO but I only activate it when I need it, and quit it when I don't, so it's not on all the time.

Also, when I change the graphics settings to choose for best appearance, for some reason it changes the Render Sampling to Native instead of Supersample. Not sure if that's a graphics card thing, but I've told you my system specs so idk why it would be choosing the worse option. I am playing using a Cintiq 22HD as a monitor, dunno if perhaps the resolution of that is why.

**Comment by megai2** [comment]
Checked this, happens only with gw2radial

**Comment by Ghostkat9** [comment]
Ah so is that the source of the issue? I really love using gw2radial, so I hope there's a fix for this so I can use both gw2radial and d912pxy without having to sacrifice one for the other. :)

**Comment by megai2** [comment]
try using alpha 2.0 of radial 
https://github.com/Friendly0Fire/GW2Radial/releases

just replace dll in addons/gw2radial

**Comment by megai2** [comment]
Any news @Ghostkat9 ?
For me it works fine with alpha radial

**Comment by Ghostkat9** [comment]
I haven't yet tried it out (busy week). I'll let you know soon as I install that.

**Comment by Thex-PiedDroit** [comment]
I had the same issue (same config, with supersampling and all), i can confirm it is fixed by the latest stable release of GW2Radial (1.2.4).
Be advised that the addon manager seems to install the alpha version of 1.2.4, so as far as i can tell, you'll have to disregard the instruction to install it through that and update it manually for the releases page.

**Comment by Ghostkat9** [comment]
> ~I had the same issue (same config, with supersampling and all), i can confirm it is fixed by the latest stable release of GW2Radial (1.2.4). Be advised that the addon manager seems to install the alpha version of 1.2.4, so as far as i can tell, you'll have to disregard the instruction to install it through that and update it manually for the releases page.~
> 
> EDIT: Nevermind, turns out i was just dumb and forgot that d912pxy has a d3d9.dll, so replacing that has simply removed it and that's why it worked...

Actually, the latest version of the GW2Radial plugin is the v2.0 Alpha, which you have to install manually. It hasn't been updated in forever, though. It does, however, produce a graphical error with the latest dx912pxy add-ons, whereby pressing the radial mount menu during load screens causes a graphical error that turns them white, and in select places it will create a white bloom or texture effect that seemingly illuminates the area around the player while the button is held down.
